//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppArcade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Message { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual user_info user_info { get; set; }
    }
}
