//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppArcade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_info()
        {
            this.UserLibraries = new HashSet<UserLibrary>();
        }
    
        public int Product_id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Image { get; set; }
        public decimal Product_Price { get; set; }
        public string Product_Category { get; set; }
        public string Product_Description { get; set; }
        public string Product_Data { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLibrary> UserLibraries { get; set; }
    }
}
