//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppArcade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLibrary
    {
        public int LibraryId { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public System.DateTime PDate { get; set; }
    
        public virtual Product_info Product_info { get; set; }
        public virtual user_info user_info { get; set; }
    }
}
